using System.Net;
using System.Text.RegularExpressions;

namespace OptimizeAll.Domain.EmailMarketing;

/// <summary>How a merge value is encoded where it is inserted.</summary>
public enum MergeContext
{
    /// <summary>HTML text or attribute value: HTML-encoded.</summary>
    Html,
    /// <summary>Plain text (text/plain part, subject, SMS): inserted as is, control characters removed.</summary>
    Text,
    /// <summary>Inside a URL: percent-encoded.</summary>
    Url,
}

/// <summary>
/// <c>{{first_name|there}}</c> merge tags. Only whitelisted names are allowed (plus <c>custom.&lt;key&gt;</c> custom
/// fields and <c>event.&lt;key&gt;</c> automation event properties); the fallback is used when the value is empty.
/// Values and fallbacks are always encoded for the context they are inserted into, so contact data can never inject
/// markup or change a link's destination host.
/// </summary>
public static partial class MergeTags
{
    public static readonly IReadOnlySet<string> Whitelist = new HashSet<string>(StringComparer.Ordinal)
    {
        "first_name", "last_name", "full_name", "email", "phone", "country", "language",
        "org_name", "org_address", "unsubscribe_url", "preferences_url", "current_year", "campaign_name",
    };

    /// <summary>System tags whose values are URLs generated by the platform (inserted without re-encoding in URLs).</summary>
    public static readonly IReadOnlySet<string> SystemUrlTags = new HashSet<string>(StringComparer.Ordinal)
    {
        "unsubscribe_url", "preferences_url",
    };

    public static bool IsAllowed(string name) =>
        Whitelist.Contains(name) ||
        (name.StartsWith("custom.", StringComparison.Ordinal) && ContactRules.IsValidFieldKey(name["custom.".Length..])) ||
        (name.StartsWith("event.", StringComparison.Ordinal) && ContactRules.IsValidFieldKey(name["event.".Length..]));

    /// <summary>Names of every merge tag used in <paramref name="text"/>.</summary>
    public static IEnumerable<string> Names(string? text) =>
        string.IsNullOrEmpty(text) ? Enumerable.Empty<string>() : TagRegex().Matches(text).Select(m => m.Groups["name"].Value);

    /// <summary>Tag names in <paramref name="text"/> that are not whitelisted.</summary>
    public static IReadOnlyList<string> Unknown(string? text) => Names(text).Where(n => !IsAllowed(n)).Distinct().ToList();

    /// <summary>Unbalanced/garbled tags such as "{{first_name" or "{{ bad name }}".</summary>
    public static bool HasMalformedTags(string? text)
    {
        if (string.IsNullOrEmpty(text)) return false;
        var stripped = TagRegex().Replace(text, string.Empty);
        return stripped.Contains("{{", StringComparison.Ordinal) || stripped.Contains("}}", StringComparison.Ordinal);
    }

    /// <summary>Replaces merge tags. Unknown tags render as empty text (they are rejected when content is saved).</summary>
    public static string Render(string? text, IReadOnlyDictionary<string, string?> values, MergeContext context)
    {
        if (string.IsNullOrEmpty(text)) return string.Empty;
        return TagRegex().Replace(text, match =>
        {
            var name = match.Groups["name"].Value;
            var fallback = match.Groups["fallback"].Success ? match.Groups["fallback"].Value.Trim() : string.Empty;
            string? value = null;
            if (IsAllowed(name)) values.TryGetValue(name, out value);
            if (string.IsNullOrWhiteSpace(value)) value = fallback;
            value = StripControl(value);
            return context switch
            {
                MergeContext.Html => WebUtility.HtmlEncode(value),
                MergeContext.Url => SystemUrlTags.Contains(name) ? value : Uri.EscapeDataString(value),
                _ => value,
            };
        });
    }

    private static string StripControl(string value) =>
        new(value.Where(c => !char.IsControl(c) || c is '\n').ToArray());

    [GeneratedRegex(@"\{\{\s*(?<name>[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)?)\s*(?:\|(?<fallback>[^{}]{0,200}))?\}\}")]
    private static partial Regex TagRegex();
}
