import {
  Activity,
  BarChart3,
  Briefcase,
  Building2,
  Clapperboard,
  Compass,
  Cpu,
  Eye,
  FileText,
  Gauge,
  GraduationCap,
  Handshake,
  HeartPulse,
  Landmark,
  LayoutTemplate,
  type LucideIcon,
  Magnet,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Mic,
  Monitor,
  MousePointerClick,
  Newspaper,
  Palette,
  PenTool,
  Rocket,
  Search,
  Share2,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Target,
  TrendingUp,
  Type,
  Users,
  Utensils,
  Video,
  Workflow,
  Wrench,
} from 'lucide-react';

/** CMS icon names (kebab-case Lucide names) → components. Unknown names fall back to a neutral icon. */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'bar-chart-3': BarChart3,
  briefcase: Briefcase,
  'building-2': Building2,
  clapperboard: Clapperboard,
  compass: Compass,
  cpu: Cpu,
  eye: Eye,
  'file-text': FileText,
  gauge: Gauge,
  'graduation-cap': GraduationCap,
  handshake: Handshake,
  'heart-pulse': HeartPulse,
  landmark: Landmark,
  'layout-template': LayoutTemplate,
  magnet: Magnet,
  mail: Mail,
  'map-pin': MapPin,
  megaphone: Megaphone,
  'message-circle': MessageCircle,
  'messages-square': MessagesSquare,
  mic: Mic,
  monitor: Monitor,
  'mouse-pointer-click': MousePointerClick,
  newspaper: Newspaper,
  palette: Palette,
  'pen-tool': PenTool,
  rocket: Rocket,
  search: Search,
  'share-2': Share2,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  store: Store,
  target: Target,
  'trending-up': TrendingUp,
  type: Type,
  users: Users,
  utensils: Utensils,
  video: Video,
  workflow: Workflow,
  wrench: Wrench,
};

export const ICON_NAMES = Object.keys(ICONS).sort();

export function SiteIcon({ name, className }: { name: string | null | undefined; className?: string }) {
  const Icon = (name && ICONS[name]) || Sparkles;
  return <Icon className={className} aria-hidden="true" focusable="false" />;
}
