using OptimizeAll.Domain.Common;

namespace OptimizeAll.Domain.Projects;

public enum ProjectType
{
    RetainerMonth,
    OneOffCampaign,
    WebsiteBuild,
    SeoProgram,
    SocialContent,
    PaidAdsLaunch,
    EmailProgram,
    Other,
}

public enum ProjectStatus
{
    Planning,
    Active,
    OnHold,
    Completed,
    Cancelled,
}

/// <summary>A piece of client work (a retainer month, campaign, website build…). Client-owned: scoped by IClientScope.</summary>
public class Project : AuditedEntity, IConcurrencyStamped
{
    public Guid ClientAccountId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public ProjectType Type { get; set; }

    /// <summary>Service line slugs, e.g. "seo", "social", "ads", "email", "content", "web", "design".</summary>
    public List<string> ServiceLines { get; set; } = new();
    public DateOnly? StartDate { get; set; }
    public DateOnly? EndDate { get; set; }
    public decimal? BudgetHours { get; set; }
    public decimal? BudgetAmount { get; set; }

    /// <summary>ISO currency of <see cref="BudgetAmount"/> (the client's currency).</summary>
    public string Currency { get; set; } = "USD";

    /// <summary>Hourly rate used for budget burn when no user or role rate applies.</summary>
    public decimal? DefaultHourlyRate { get; set; }
    public ProjectStatus Status { get; set; } = ProjectStatus.Planning;
    public Guid? OwnerUserId { get; set; }

    /// <summary>Template the project was created from (for reference).</summary>
    public string? TemplateKey { get; set; }
    public Guid? CreatedByUserId { get; set; }
    public Guid ConcurrencyStamp { get; set; } = Guid.NewGuid();

    public bool IsRetainer => Type is ProjectType.RetainerMonth or ProjectType.SeoProgram or ProjectType.SocialContent;
}

public class ProjectMember
{
    public Guid ProjectId { get; set; }
    public Guid UserId { get; set; }
    public DateTime AddedAt { get; set; }
}

public enum MilestoneStatus
{
    Open,
    Done,
}

public class Milestone : Entity
{
    public Guid ProjectId { get; set; }
    public Guid ClientAccountId { get; set; }
    public string Title { get; set; } = string.Empty;
    public DateOnly? DueDate { get; set; }
    public MilestoneStatus Status { get; set; } = MilestoneStatus.Open;
    public int SortOrder { get; set; }
    public bool ClientVisible { get; set; } = true;
    public DateTime? CompletedAt { get; set; }
}

public enum ProjectTaskStatus
{
    Todo,
    InProgress,
    InReview,
    Blocked,
    Done,
}

public enum TaskPriority
{
    Low,
    Normal,
    High,
    Urgent,
}

/// <summary>A unit of work on a project. Kanban position is <see cref="SortOrder"/> within its status column.</summary>
public class ProjectTask : AuditedEntity, IConcurrencyStamped
{
    public Guid ProjectId { get; set; }
    public Guid ClientAccountId { get; set; }
    public Guid? MilestoneId { get; set; }
    public string Title { get; set; } = string.Empty;

    /// <summary>Markdown.</summary>
    public string? Description { get; set; }
    public ProjectTaskStatus Status { get; set; } = ProjectTaskStatus.Todo;
    public TaskPriority Priority { get; set; } = TaskPriority.Normal;
    public DateOnly? DueDate { get; set; }
    public decimal? EstimateHours { get; set; }
    public List<string> Labels { get; set; } = new();

    /// <summary>Shown (title, status, due date, milestone) in the client portal's project view.</summary>
    public bool ClientVisible { get; set; }
    public double SortOrder { get; set; }
    public DateTime? CompletedAt { get; set; }
    public Guid? CreatedByUserId { get; set; }

    /// <summary>Set on tasks generated by a <see cref="RecurringTaskRule"/>: "{ruleId}:{yyyy-MM}" (unique → idempotent).</summary>
    public string? RecurrenceKey { get; set; }
    public Guid? BriefId { get; set; }
    public Guid? MeetingId { get; set; }
    public Guid ConcurrencyStamp { get; set; } = Guid.NewGuid();
}

public class TaskAssignee
{
    public Guid TaskId { get; set; }
    public Guid UserId { get; set; }
}

public class TaskWatcher
{
    public Guid TaskId { get; set; }
    public Guid UserId { get; set; }
}

public class TaskChecklistItem : Entity
{
    public Guid TaskId { get; set; }
    public string Text { get; set; } = string.Empty;
    public bool IsDone { get; set; }
    public int SortOrder { get; set; }
}

/// <summary>"<see cref="TaskId"/> is blocked by <see cref="BlockedByTaskId"/>" (same project).</summary>
public class TaskDependency
{
    public Guid TaskId { get; set; }
    public Guid BlockedByTaskId { get; set; }
}

public class TaskComment : Entity
{
    public Guid TaskId { get; set; }
    public Guid ClientAccountId { get; set; }
    public Guid AuthorUserId { get; set; }
    public string Body { get; set; } = string.Empty;

    /// <summary>Users mentioned (validated staff ids); each is notified once.</summary>
    public List<Guid> MentionedUserIds { get; set; } = new();
    public DateTime CreatedAt { get; set; }

    /// <summary>Set when the author edited the comment (shown as "edited").</summary>
    public DateTime? EditedAt { get; set; }
}

public class TaskAttachment : Entity
{
    public Guid TaskId { get; set; }
    public Guid FileId { get; set; }
    public Guid AddedByUserId { get; set; }
    public DateTime CreatedAt { get; set; }
}

/// <summary>Generates a task every month on <see cref="DayOfMonth"/> (e.g. the monthly report).</summary>
public class RecurringTaskRule : AuditedEntity
{
    public Guid ProjectId { get; set; }
    public Guid ClientAccountId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }

    /// <summary>1–28.</summary>
    public int DayOfMonth { get; set; } = 1;

    /// <summary>Days after generation the task is due.</summary>
    public int DueInDays { get; set; } = 5;
    public Guid? AssigneeUserId { get; set; }
    public decimal? EstimateHours { get; set; }
    public List<string> Labels { get; set; } = new();
    public bool ClientVisible { get; set; }
    public bool IsActive { get; set; } = true;
}

// ---------------------------------------------------------------- templates (reference data)

public sealed record TemplateMilestone(string Key, string Title, int OffsetDays);

public sealed record TemplateTask(
    string Title, string? Description, string? MilestoneKey, int OffsetDays, decimal? EstimateHours, List<string> Labels,
    bool ClientVisible, string? DeliverableType = null);

public sealed record TemplateRecurring(string Title, string? Description, int DayOfMonth, int DueInDays, decimal? EstimateHours, List<string> Labels);

/// <summary>A service template: creating a project from it creates its milestones, tasks and recurring rules.</summary>
public class ProjectTemplate : AuditedEntity, IConcurrencyStamped
{
    public string Key { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public ProjectType ProjectType { get; set; }
    public List<string> ServiceLines { get; set; } = new();
    public decimal? DefaultBudgetHours { get; set; }
    public int? DurationDays { get; set; }
    public List<TemplateMilestone> Milestones { get; set; } = new();
    public List<TemplateTask> Tasks { get; set; } = new();
    public List<TemplateRecurring> Recurring { get; set; } = new();
    public bool IsActive { get; set; } = true;
    public Guid ConcurrencyStamp { get; set; } = Guid.NewGuid();
}

/// <summary>A private file of a client (deliverable version, task/message attachment, brand asset, logo).</summary>
public class DeliveryFile : Entity
{
    public Guid ClientAccountId { get; set; }
    public string StorageKey { get; set; } = string.Empty;
    public string ContentType { get; set; } = string.Empty;
    public long SizeBytes { get; set; }
    public string Sha256 { get; set; } = string.Empty;
    public string OriginalFileName { get; set; } = string.Empty;
    public Guid UploadedByUserId { get; set; }
    public DateTime CreatedAt { get; set; }
}

/// <summary>Idempotency keys for notifications/reminders sent by delivery jobs (SLA reminders, report emails…).</summary>
public class DeliveryDispatchKey
{
    public string Key { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
}
