using OptimizeAll.Domain.Website;

namespace OptimizeAll.Api.Modules.Website.Seed;

internal sealed record PackageSeed(
    string Name, string Description, decimal? Price, PackageBillingPeriod Period, decimal? SetupFee, bool Popular, string[] Features);

internal sealed record ServiceSeed(
    string Slug, string Name, string Icon, string Tagline, string HeroBody, string Overview, string[] Problems, string[] Deliverables,
    string[] Tools, string[] Kpis, (string Q, string A)[] Faqs, PackageSeed[] Packages, string[]? Related = null, string? CtaLabel = null,
    string? CtaUrl = null, bool Featured = false);

internal sealed record CategorySeed(string Slug, string Name, string Icon, string Description, (string Title, string Text)[] Process, ServiceSeed[] Services);

/// <summary>
/// The agency's baseline service catalog: nine service lines and their services, with real, publishable copy and
/// starting packages. Prices are list prices in USD that the agency should review before launch; everything can be edited
/// in the CMS afterwards (the seed never overwrites existing rows).
/// </summary>
internal static class BaselineServices
{
    private static PackageSeed[] Tiers(decimal starter, decimal growth, string[] starterFeatures, string[] growthFeatures, string[] scaleFeatures,
        decimal? setup = null, PackageBillingPeriod period = PackageBillingPeriod.Monthly, decimal? scale = null) => new[]
    {
        new PackageSeed("Starter", "For businesses laying the foundations.", starter, period, setup, false, starterFeatures),
        new PackageSeed("Growth", "Our most chosen plan for steady, compounding growth.", growth, period, setup, true, growthFeatures),
        new PackageSeed("Scale", "For ambitious teams that need senior strategy and more output.", scale, period, scale is null ? null : setup, false, scaleFeatures),
    };

    private static PackageSeed[] Projects(decimal starter, decimal growth, string[] starterFeatures, string[] growthFeatures, string[] scaleFeatures) =>
        Tiers(starter, growth, starterFeatures, growthFeatures, scaleFeatures, null, PackageBillingPeriod.OneTime);

    private static readonly (string, string)[] SearchProcess =
    {
        ("Audit", "We benchmark your technical health, content and authority against the competitors that outrank you today."),
        ("Strategy", "A prioritised roadmap: the keywords worth winning, the pages to build or fix, and the links you need."),
        ("Execution", "Our specialists ship fixes, content and outreach every month — documented in a shared tracker."),
        ("Reporting", "Monthly reporting on rankings, organic traffic and the conversions they drive, with next steps."),
    };

    private static readonly (string, string)[] SocialProcess =
    {
        ("Discover", "We learn your audience, voice and goals, and audit what already works on your channels."),
        ("Plan", "A content and channel plan with pillars, formats, posting cadence and success metrics."),
        ("Create & engage", "We produce, schedule and publish content, and manage conversations in your brand voice."),
        ("Measure & refine", "Monthly insights on reach, engagement and conversions — and what we'll change next."),
    };

    private static readonly (string, string)[] PaidProcess =
    {
        ("Account audit", "We review tracking, structure, targeting and spend to find wasted budget and quick wins."),
        ("Build", "Conversion tracking, campaign architecture, audiences and creative built for testing."),
        ("Optimise", "Weekly bid, budget, audience and creative optimisation against your target CPA or ROAS."),
        ("Scale", "We scale what works, open new channels and report on revenue — not just clicks."),
    };

    private static readonly (string, string)[] ContentProcess =
    {
        ("Research", "Audience, keyword and competitor research to find the topics that attract buyers."),
        ("Plan", "An editorial calendar with briefs, formats and distribution for every piece."),
        ("Produce", "Writers, editors, videographers and designers create on-brand content, reviewed by you."),
        ("Distribute & measure", "We publish, promote and track each piece's traffic, engagement and leads."),
    };

    private static readonly (string, string)[] EmailProcess =
    {
        ("Audit", "We review your list health, deliverability, flows and campaign performance."),
        ("Architect", "Segments, lifecycle flows and a campaign calendar mapped to your customer journey."),
        ("Build & send", "Templates, copy and automations built, tested and sent on schedule."),
        ("Optimise", "A/B tests and reporting on revenue per recipient, conversions and list growth."),
    };

    private static readonly (string, string)[] BrandProcess =
    {
        ("Discovery", "Workshops and research to understand your business, customers and competitors."),
        ("Concepts", "Strategic directions and design concepts for you to react to."),
        ("Design & build", "We refine the chosen direction and build it to a high standard, with regular reviews."),
        ("Launch & handover", "Launch support, documentation and training so your team can run with it."),
    };

    private static readonly (string, string)[] GrowthProcess =
    {
        ("Diagnose", "We map your funnel end to end and find the biggest constraints on growth."),
        ("Design", "A growth plan with experiments, systems and the metrics that prove success."),
        ("Implement", "We build the programmes, automations and integrations — and document them."),
        ("Iterate", "Weekly experiments and monthly reviews focused on pipeline and revenue."),
    };

    private static readonly (string, string)[] ReputationProcess =
    {
        ("Listen", "We audit what customers, journalists and search results say about you today."),
        ("Plan", "A reputation and PR plan with priorities, messages and target outlets."),
        ("Act", "Review generation, responses, story pitching and outreach — handled by specialists."),
        ("Report", "Monthly reporting on ratings, sentiment, coverage and authority gained."),
    };

    private static readonly (string, string)[] StrategyProcess =
    {
        ("Discover", "Stakeholder interviews, data review and market research."),
        ("Analyse", "We find where growth will come from and what's holding it back."),
        ("Recommend", "A clear plan: priorities, budgets, channels, owners and targets."),
        ("Enable", "Implementation support, dashboards and check-ins to keep the plan on track."),
    };

    public static readonly CategorySeed[] Categories =
    {
        new("search", "Search", "search", "Get found by customers who are already looking for what you sell.", SearchProcess, new ServiceSeed[]
        {
            new("seo", "SEO", "search", "Rank for the searches that bring buyers, not just visitors.",
                "Search engine optimisation that combines technical excellence, genuinely useful content and authority building — measured in leads and revenue.",
                "Organic search is still the channel with the highest intent and the lowest marginal cost. Our SEO programmes start with an honest audit of where you stand, then focus effort on the keywords and pages most likely to convert.\n\nEvery month you'll see what we shipped, what moved and what we'll do next. No black boxes, no link schemes, no vanity rankings.",
                new[] { "Your competitors outrank you for the terms your customers search", "Organic traffic has plateaued or dropped after an algorithm update", "You publish content but it doesn't bring leads", "Nobody owns SEO in-house, so fixes never ship" },
                new[] { "Technical SEO audit and fix roadmap", "Keyword and competitor research", "On-page optimisation of priority pages", "Content briefs and new landing pages", "Ethical link building and digital PR", "Monthly reporting on rankings, traffic and conversions" },
                new[] { "Google Search Console", "GA4", "Ahrefs", "Semrush", "Screaming Frog", "Looker Studio" },
                new[] { "Organic sessions", "Non-branded keyword rankings", "Organic leads and revenue", "Share of search" },
                new[] { ("How long does SEO take to work?", "Most sites see meaningful movement in 3–6 months, depending on competition, site health and how quickly changes can be shipped. Quick technical wins often show sooner."),
                        ("Do you guarantee first-page rankings?", "No honest agency can: Google decides rankings. We commit to a transparent plan, consistent execution and reporting on the outcomes that matter to your business."),
                        ("Will you need access to our website?", "Yes — ideally CMS and Search Console access so we can ship fixes. If your developers prefer to implement changes, we provide clear tickets.") },
                Tiers(1500, 3500, new[] { "Technical audit and fixes for up to 50 pages", "10 target keywords", "2 optimised pages per month", "Monthly report" },
                    new[] { "Everything in Starter", "30 target keywords", "4 content pieces or landing pages per month", "Link building and digital PR", "Quarterly strategy review" },
                    new[] { "Everything in Growth", "Unlimited keywords and multiple markets", "Dedicated SEO lead", "International and enterprise SEO", "Weekly check-ins" }),
                new[] { "technical-seo", "local-seo-google-business-profile", "blog-article-writing" }, Featured: true),
            new("local-seo-google-business-profile", "Local SEO & Google Business Profile", "map-pin", "Win the map pack in every area you serve.",
                "Optimised Google Business Profiles, consistent citations and a steady flow of reviews so nearby customers choose you.",
                "For businesses that serve customers locally, the map pack is often worth more than the top organic result. We optimise your Google Business Profile, clean up listings across directories and build local landing pages that rank.\n\nMulti-location brands get location-level reporting, so you can see which branches win calls, direction requests and bookings.",
                new[] { "You don't appear in the map pack for '[service] near me'", "Your business details are inconsistent across directories", "Competitors have more — and better — reviews", "Multi-location reporting is a spreadsheet nightmare" },
                new[] { "Google Business Profile optimisation", "Citation audit and clean-up", "Local landing pages", "Review generation programme", "GBP posts and Q&A management", "Location-level reporting" },
                new[] { "Google Business Profile", "BrightLocal", "Whitespark", "GA4" },
                new[] { "Map pack visibility", "Calls and direction requests", "Review count and rating", "Local organic leads" },
                new[] { ("Can you help with multiple locations?", "Yes. We manage profiles and reporting for single sites and multi-location brands alike."),
                        ("Do you write fake reviews?", "Never. We set up compliant programmes that ask real customers for honest reviews at the right moment.") },
                Tiers(450, 900, new[] { "1 location", "Profile optimisation", "Monthly GBP posts", "Citation clean-up" },
                    new[] { "Up to 3 locations", "Review generation programme", "Local landing pages", "Monthly reporting" },
                    new[] { "4+ locations", "Location-level dashboards", "Reputation monitoring", "Dedicated account manager" }),
                new[] { "seo", "online-reputation-management" }),
            new("technical-seo", "Technical SEO", "wrench", "Fix what stops search engines crawling, rendering and ranking you.",
                "Deep technical audits and hands-on fixes for site speed, Core Web Vitals, indexing, structured data and migrations.",
                "Great content can't rank if search engines struggle to crawl, render or understand your site. Our technical SEO specialists find the issues that hold you back and work with your developers to fix them.\n\nWe're especially useful before and during site migrations, platform changes and international expansion — where mistakes are expensive.",
                new[] { "Pages aren't indexed or keep dropping out", "Slow pages and poor Core Web Vitals", "A site migration is coming and you can't afford to lose traffic", "JavaScript frameworks hide content from crawlers" },
                new[] { "Crawl, index and render audit", "Core Web Vitals and speed plan", "Structured data implementation", "Migration planning and QA", "Log file analysis", "Developer-ready tickets" },
                new[] { "Screaming Frog", "Google Search Console", "PageSpeed Insights", "Chrome DevTools", "Sitebulb" },
                new[] { "Indexed pages", "Core Web Vitals pass rate", "Crawl errors", "Organic traffic retained after migration" },
                new[] { ("Do you implement fixes or just report them?", "Both. We can implement directly in most CMSs, or hand your developers precise tickets and QA the result."),
                        ("Can you help with a website migration?", "Yes — migrations are one of our specialities. We plan redirects, benchmark performance and monitor closely after launch.") },
                Projects(2500, 6000, new[] { "Technical audit up to 5,000 URLs", "Prioritised fix roadmap", "1 walkthrough call" },
                    new[] { "Everything in Starter", "Up to 50,000 URLs", "Implementation support for 60 days", "Core Web Vitals plan" },
                    new[] { "Enterprise sites and migrations", "Log file analysis", "Launch-day monitoring", "Post-migration recovery plan" }),
                new[] { "seo", "web-design-development" }),
            new("app-store-optimization", "App Store Optimization", "smartphone", "More installs from the App Store and Google Play.",
                "Keyword-optimised listings, conversion-focused creative and review management for iOS and Android apps.",
                "App store search drives the majority of app installs. We research the terms your users search, optimise titles, subtitles and descriptions, and test screenshots and preview videos that convert browsers into users.\n\nWe also help you respond to reviews and turn feedback into better ratings.",
                new[] { "Your app is hard to find in store search", "Store visitors don't install", "Ratings are dragging down conversions", "Paid installs are getting expensive" },
                new[] { "Keyword research for iOS and Google Play", "Metadata optimisation", "Screenshot and video creative", "A/B tests with store experiments", "Review response programme", "Monthly reporting" },
                new[] { "App Store Connect", "Google Play Console", "AppTweak", "Sensor Tower" },
                new[] { "Keyword rankings", "Store conversion rate", "Organic installs", "Average rating" },
                new[] { ("Do you work on both iOS and Android?", "Yes, and we optimise each store separately because their algorithms and audiences differ.") },
                Tiers(1200, 2500, new[] { "1 platform", "Keyword research", "Metadata optimisation", "Monthly report" },
                    new[] { "iOS and Android", "Creative testing", "Review responses", "Localisation for 2 markets" },
                    new[] { "Multiple apps or markets", "Full creative production", "Paid UA alignment", "Dedicated specialist" })),
        }),
        new("social", "Social", "share-2", "Build an audience that trusts you — and buys from you.", SocialProcess, new ServiceSeed[]
        {
            new("social-media-management", "Social Media Management", "share-2", "Consistent, on-brand social that grows an engaged audience.",
                "Strategy, content creation, scheduling and reporting across Instagram, Facebook, LinkedIn, TikTok and X.",
                "Social media works when it's consistent, useful and unmistakably yours. We plan content pillars around your goals, create posts, carousels and short videos, and publish them at the times your audience is active.\n\nYou approve everything before it goes live, and monthly reports show what's working and what we'll change.",
                new[] { "Posting is inconsistent because nobody has time", "Content doesn't reflect your brand", "Followers grow but nothing converts", "You can't tell what's working" },
                new[] { "Social strategy and content pillars", "Monthly content calendar", "Post, carousel and short-video creation", "Scheduling and publishing", "Hashtag and trend research", "Monthly performance report" },
                new[] { "Meta Business Suite", "LinkedIn", "TikTok", "Canva", "Adobe Creative Cloud", "Sprout Social" },
                new[] { "Engagement rate", "Follower growth", "Profile visits and link clicks", "Social-sourced leads" },
                new[] { ("Which platforms do you manage?", "Instagram, Facebook, LinkedIn, TikTok, X, Pinterest and YouTube Shorts. We'll recommend the channels that fit your audience."),
                        ("Do we approve content before it's posted?", "Always. You'll review a monthly calendar and can comment on or approve every post in the client portal.") },
                Tiers(900, 1800, new[] { "2 platforms", "12 posts per month", "Content calendar", "Monthly report" },
                    new[] { "3 platforms", "20 posts per month incl. 4 short videos", "Community management (weekdays)", "Quarterly strategy review" },
                    new[] { "Up to 5 platforms", "Daily posting and stories", "Dedicated social lead", "Always-on community management" }),
                new[] { "community-management", "social-media-advertising", "influencer-ugc-marketing" }, Featured: true),
            new("community-management", "Community Management", "messages-square", "Every comment and message answered in your brand voice.",
                "We monitor and respond to comments, DMs and mentions, escalate issues fast and turn conversations into customers.",
                "People expect brands to reply — quickly and like a human. Our community managers handle comments, direct messages and mentions to your agreed tone of voice and response times, and route sales leads and support issues to the right people.\n\nYou'll get insight into what your audience asks for, complains about and loves.",
                new[] { "Messages and comments go unanswered", "Negative comments escalate before anyone notices", "Sales enquiries get lost in DMs", "No insight into what customers are saying" },
                new[] { "Response playbook and tone-of-voice guide", "Comment and DM management", "Escalation workflow", "Social listening for brand mentions", "Weekly insights digest" },
                new[] { "Sprout Social", "Meta Business Suite", "Brandwatch", "Slack" },
                new[] { "Response time", "Response rate", "Sentiment", "Conversations converted to leads" },
                new[] { ("What hours do you cover?", "Standard plans cover weekdays in your time zone; extended and weekend coverage is available.") },
                Tiers(700, 1400, new[] { "2 platforms", "Weekday coverage", "Response within 1 business day" },
                    new[] { "4 platforms", "Response within 4 business hours", "Social listening", "Weekly insights" },
                    new[] { "All platforms", "7-day coverage", "1-hour response SLA", "Crisis support" }),
                new[] { "social-media-management", "online-reputation-management" }),
            new("influencer-ugc-marketing", "Influencer & UGC Marketing", "users", "Real creators, real posts, clearly disclosed — and paid only for what's approved.",
                "Run influencer and user-generated-content campaigns through our creator network: vetted established accounts share your approved content, every post is human-reviewed and disclosed.",
                "Optimize All began as a platform that pays everyday creators to share brands they believe in. Today that network powers our Influencer & UGC service: you provide the brief and approved content, established creators share it from their own accounts, and our review team checks every post before it's paid.\n\nBecause creators are paid per approved post, you only pay for content that actually went live, met your rules and carried the required paid-partnership disclosure.",
                new[] { "Influencer campaigns are hard to measure and harder to trust", "Fake followers and engagement waste budget", "You need authentic UGC at scale for ads and social", "Disclosure rules make you nervous" },
                new[] { "Campaign brief and creator eligibility rules", "Recruitment from our vetted creator network", "Approved content kits and disclosure guidance", "Human review of every submitted post", "Pay-per-approved-post rewards and payouts", "Campaign reporting on reach and engagement" },
                new[] { "Optimize All creator platform", "Instagram", "TikTok", "YouTube", "Facebook" },
                new[] { "Approved posts", "Estimated reach", "Engagement rate", "Cost per approved post" },
                new[] { ("How do you prevent fake accounts?", "Creators must share from established accounts that meet minimum age and audience rules. Each account is verified, and reviewers check every post before it's approved."),
                        ("Are posts disclosed as paid?", "Always. Paid-partnership labels or disclosure text are mandatory, and posts without them are rejected."),
                        ("Can I become a creator?", "Yes — if you have an established social account, you can join the creator program and get paid to share campaigns you like.") },
                Tiers(2000, 5000, new[] { "1 campaign per month", "Up to 50 approved posts", "Content kit and brief", "Campaign report" },
                    new[] { "2 campaigns per month", "Up to 200 approved posts", "UGC rights for ads", "Creator targeting by country and niche" },
                    new[] { "Always-on creator programme", "Custom eligibility rules", "Dedicated campaign manager", "Paid amplification of top posts" }, setup: 500),
                new[] { "social-media-advertising", "social-media-management" }, "Join as a creator", "/creators", Featured: true),
            new("social-media-advertising", "Social Media Advertising", "megaphone", "Paid social that turns scroll-stopping creative into customers.",
                "Full-funnel campaigns on Meta, TikTok, LinkedIn, Pinterest and Snapchat — with creative testing built in.",
                "Paid social rewards brands that test relentlessly. We build audience strategies across the funnel, produce and iterate on creative, and optimise daily against the metric that matters to you — whether that's leads, purchases or app installs.\n\nClean tracking and honest reporting mean you always know what your budget is doing.",
                new[] { "Rising CPMs and falling returns", "Creative fatigue after a few weeks", "Unclear attribution between platforms", "Campaigns set up years ago and never restructured" },
                new[] { "Paid social strategy and audience plan", "Pixel and Conversions API setup", "Ad creative production and testing", "Campaign build and daily optimisation", "Retargeting and lookalike programmes", "Weekly performance updates" },
                new[] { "Meta Ads Manager", "TikTok Ads Manager", "LinkedIn Campaign Manager", "Pinterest Ads", "GA4" },
                new[] { "Return on ad spend", "Cost per acquisition", "Click-through rate", "Creative win rate" },
                new[] { ("Is ad spend included in the fee?", "No. Our fee covers strategy, creative and management; ad spend is billed by the platforms directly to your account."),
                        ("What budget do we need?", "We recommend at least $1,500 per month in ad spend per platform to gather enough data to optimise.") },
                Tiers(1200, 2500, new[] { "1 platform", "Up to $10k monthly spend", "4 new ad creatives per month", "Monthly report" },
                    new[] { "2 platforms", "Up to $50k monthly spend", "10 new ad creatives per month", "Weekly updates" },
                    new[] { "All platforms", "$50k+ monthly spend", "Creative studio and UGC", "Dedicated media buyer" }, setup: 750),
                new[] { "meta-ads", "tiktok-linkedin-ads", "influencer-ugc-marketing" }),
        }),
        new("paid-media", "Paid Media", "mouse-pointer-click", "Profitable growth from every dollar of ad spend.", PaidProcess, new ServiceSeed[]
        {
            new("google-ads-ppc", "Google Ads / PPC", "mouse-pointer-click", "Capture demand the moment customers search for it.",
                "Search, Performance Max, YouTube and Demand Gen campaigns managed by certified specialists against your target CPA or ROAS.",
                "Google Ads can be your most profitable channel or your most wasteful. We restructure accounts around intent, tighten match types and negatives, fix conversion tracking and write ads that earn the click.\n\nThen we optimise weekly — bids, budgets, landing pages and creative — and report on the revenue your ads generate.",
                new[] { "High spend, low return", "Broad match and Performance Max eating budget", "Conversion tracking you don't trust", "No time to test ads and landing pages" },
                new[] { "Account audit and restructure", "Conversion tracking and offline conversion import", "Keyword and negative keyword strategy", "Ad copy and extension testing", "Landing page recommendations", "Weekly optimisation and monthly reporting" },
                new[] { "Google Ads", "Google Tag Manager", "GA4", "Google Merchant Center", "Optmyzr" },
                new[] { "Cost per acquisition", "Return on ad spend", "Conversion rate", "Impression share" },
                new[] { ("Do you require a long contract?", "No. After an initial three-month period, plans run month to month."),
                        ("Who owns the ad account?", "You do. We work in your account so all data and history stay with you.") },
                Tiers(1000, 2200, new[] { "Up to $10k monthly spend", "Search campaigns", "Conversion tracking", "Monthly report" },
                    new[] { "Up to $50k monthly spend", "Search, PMax and YouTube", "Landing page testing", "Bi-weekly calls" },
                    new[] { "$50k+ monthly spend", "Multi-market accounts", "Offline conversion import", "Dedicated PPC lead" }, setup: 750),
                new[] { "shopping-ecommerce-ads", "landing-pages-cro", "analytics-tracking-setup" }, Featured: true),
            new("meta-ads", "Meta Ads", "target", "Facebook and Instagram ads that sell — measured properly.",
                "Advantage+ and manual campaigns, Conversions API, creative testing and full-funnel audiences on Facebook and Instagram.",
                "Meta's algorithms reward clean signals and fresh creative. We set up the Conversions API, simplify account structure so the algorithm can learn, and run a steady cadence of creative tests to find the angles that convert.\n\nYou get weekly insight into what's winning and why.",
                new[] { "Performance dropped after iOS privacy changes", "Ad fatigue within weeks", "Too many small ad sets that never exit learning", "Reports that don't match your sales data" },
                new[] { "Pixel and Conversions API setup", "Account restructure", "Creative testing framework", "Advantage+ shopping and app campaigns", "Retargeting and lookalikes", "Weekly reporting" },
                new[] { "Meta Ads Manager", "Meta Events Manager", "GA4", "Triple Whale" },
                new[] { "ROAS", "Cost per purchase or lead", "Creative hit rate", "Frequency" },
                new[] { ("Do you create the ads too?", "Yes. Creative production is included in Growth and Scale plans, and our UGC network can supply authentic creator content.") },
                Tiers(1000, 2200, new[] { "Up to $10k monthly spend", "4 new creatives per month", "Conversions API setup", "Monthly report" },
                    new[] { "Up to $50k monthly spend", "10 new creatives per month", "Weekly reporting", "UGC creative sourcing" },
                    new[] { "$50k+ monthly spend", "Creative studio", "Incrementality testing", "Dedicated media buyer" }, setup: 750),
                new[] { "social-media-advertising", "influencer-ugc-marketing" }),
            new("tiktok-linkedin-ads", "TikTok & LinkedIn Ads", "clapperboard", "Reach new audiences where they actually pay attention.",
                "Native-feeling TikTok creative for consumer brands and precise LinkedIn targeting for B2B pipelines.",
                "TikTok and LinkedIn are very different channels with one thing in common: generic ads fail. For TikTok we produce creator-style videos built around trends and hooks; for LinkedIn we target accounts, job titles and seniority with thought-leadership and lead-gen formats.\n\nBoth are measured against pipeline and revenue, not views.",
                new[] { "Your brand isn't on TikTok yet and you don't know where to start", "LinkedIn leads are expensive and low quality", "Repurposed Instagram ads flop on TikTok", "Sales doesn't trust paid social leads" },
                new[] { "Channel strategy and audience plan", "TikTok-native video production", "LinkedIn lead-gen and conversation ads", "Account-based targeting lists", "CRM lead sync", "Monthly reporting on pipeline" },
                new[] { "TikTok Ads Manager", "LinkedIn Campaign Manager", "HubSpot", "Salesforce" },
                new[] { "Cost per qualified lead", "Pipeline influenced", "Video completion rate", "Cost per acquisition" },
                new[] { ("Which is right for us — TikTok or LinkedIn?", "Consumer brands usually start with TikTok; B2B and high-ticket services with LinkedIn. We'll recommend based on your audience and deal size.") },
                Tiers(1200, 2500, new[] { "1 platform", "Up to $10k monthly spend", "4 creatives per month" },
                    new[] { "Both platforms", "Up to $40k monthly spend", "8 creatives per month", "CRM integration" },
                    new[] { "$40k+ monthly spend", "Account-based programmes", "Creator partnerships", "Dedicated specialist" }, setup: 750),
                new[] { "social-media-advertising", "lead-generation" }),
            new("programmatic-display", "Programmatic & Display", "monitor", "Reach the right people across the open web, at scale.",
                "Programmatic display, video and CTV campaigns with audience targeting, brand safety and frequency control.",
                "Programmatic advertising lets you reach specific audiences across thousands of websites, apps and streaming services. We plan and buy media through leading demand-side platforms, apply strict brand-safety and fraud controls, and measure incremental impact.\n\nIdeal for awareness, retargeting and reaching audiences that search and social can't.",
                new[] { "You've hit the ceiling of search and social", "Display campaigns deliver impressions but no results", "Worries about brand safety and ad fraud", "No way to measure upper-funnel impact" },
                new[] { "Media plan and audience strategy", "DSP campaign setup", "Display, video and CTV creative specs", "Brand-safety and fraud controls", "Frequency and reach management", "Incrementality reporting" },
                new[] { "Google Display & Video 360", "The Trade Desk", "IAS", "DoubleVerify" },
                new[] { "Reach and frequency", "Viewability", "Cost per incremental visit", "Brand lift" },
                new[] { ("What's the minimum budget?", "Programmatic works best from around $10,000 per month in media spend.") },
                Tiers(1800, 3500, new[] { "Display retargeting", "Up to $20k monthly spend", "Brand-safety controls" },
                    new[] { "Display and video", "Up to $75k monthly spend", "Audience prospecting", "Incrementality tests" },
                    new[] { "CTV and audio", "$75k+ monthly spend", "Private marketplace deals", "Dedicated trader" }, setup: 1000),
                new[] { "google-ads-ppc", "analytics-tracking-setup" }),
            new("shopping-ecommerce-ads", "Shopping & E-commerce Ads", "shopping-cart", "Put your products in front of shoppers ready to buy.",
                "Google Shopping, Performance Max, Meta catalogue and marketplace ads powered by an optimised product feed.",
                "Your product feed is your ad copy. We optimise titles, attributes and images, structure campaigns by margin and performance, and run dynamic retargeting across Google and Meta.\n\nFor marketplace sellers we also manage Amazon Sponsored Products and Brands.",
                new[] { "Products disapproved in Merchant Center", "Bestsellers get all the budget while new lines never show", "ROAS is fine overall but hides loss-making products", "Feed data is messy and hard to fix" },
                new[] { "Product feed audit and optimisation", "Merchant Center setup and health", "Shopping and Performance Max structure", "Dynamic product retargeting", "Margin-based bidding", "Product-level reporting" },
                new[] { "Google Merchant Center", "Google Ads", "Meta Commerce Manager", "Feedonomics", "Amazon Ads" },
                new[] { "ROAS", "Revenue", "Product-level profit", "Feed approval rate" },
                new[] { ("Do you work with Shopify and WooCommerce?", "Yes — along with BigCommerce, Magento and custom platforms.") },
                Tiers(1200, 2500, new[] { "Up to 500 SKUs", "Google Shopping", "Feed optimisation" },
                    new[] { "Up to 5,000 SKUs", "Google and Meta catalogue ads", "Margin-based structure" },
                    new[] { "Large catalogues", "Marketplaces incl. Amazon", "Multi-country feeds", "Dedicated specialist" }, setup: 750),
                new[] { "google-ads-ppc", "ecommerce-growth" }),
        }),
        new("content", "Content", "pen-tool", "Content that earns attention, trust and search traffic.", ContentProcess, new ServiceSeed[]
        {
            new("content-marketing-strategy", "Content Marketing & Strategy", "pen-tool", "A content engine tied to revenue, not just publishing volume.",
                "Audience research, messaging, editorial planning and distribution strategy that turn content into pipeline.",
                "Most content fails because it's written for the brand, not the buyer. We research your audience's questions and objections, map content to every stage of the journey and build an editorial calendar your team can actually deliver.\n\nThen we measure each piece against traffic, engagement and the leads it influences.",
                new[] { "You publish regularly but can't show ROI", "Content ideas run dry", "Sales says marketing content doesn't help them", "No documented strategy or tone of voice" },
                new[] { "Audience and competitor research", "Messaging and tone-of-voice guide", "Content pillars and topic clusters", "12-month editorial calendar", "Distribution and repurposing plan", "Content performance dashboard" },
                new[] { "Semrush", "SparkToro", "Notion", "GA4", "HubSpot" },
                new[] { "Content-influenced pipeline", "Organic traffic", "Engagement time", "Content-assisted conversions" },
                new[] { ("Do you also create the content?", "Yes — our copywriting, blog and video teams can produce everything in the plan, or we can brief your in-house team.") },
                Projects(3500, 7500, new[] { "Audience research", "Content pillars", "3-month calendar" },
                    new[] { "Everything in Starter", "Messaging and tone of voice", "12-month calendar", "Distribution plan" },
                    new[] { "Full content strategy", "Measurement framework", "Team workshops", "Quarterly reviews for a year" }),
                new[] { "blog-article-writing", "copywriting", "seo" }),
            new("copywriting", "Copywriting", "type", "Words that make people act.",
                "Conversion-focused copy for websites, landing pages, ads, emails and sales materials.",
                "Good copy is clear before it's clever. Our copywriters interview your team and customers, find the words your buyers use, and write copy that explains your value quickly and moves readers to act.\n\nEvery project includes two rounds of revisions.",
                new[] { "Your website says what you do, not why it matters", "Ads and emails underperform", "Messaging is inconsistent across channels", "Nobody on the team enjoys writing" },
                new[] { "Customer and stakeholder interviews", "Website and landing page copy", "Ad and email copy", "Product and category descriptions", "Sales decks and one-pagers", "Two rounds of revisions" },
                new[] { "Google Docs", "Hemingway", "Grammarly", "Figma" },
                new[] { "Conversion rate", "Click-through rate", "Time on page", "Reply and response rates" },
                new[] { ("Can you write in our brand voice?", "Yes. We start from your tone-of-voice guide — or create one — and match it consistently.") },
                Projects(900, 2500, new[] { "Landing page or 5 ad sets", "1 interview", "2 revision rounds" },
                    new[] { "Website up to 8 pages", "Customer interviews", "SEO optimisation", "2 revision rounds" },
                    new[] { "Full website and campaign copy", "Messaging framework", "Ongoing retainer available" }),
                new[] { "landing-pages-cro", "content-marketing-strategy" }),
            new("blog-article-writing", "Blog & Article Writing", "file-text", "Expert articles that rank and convert.",
                "SEO-optimised blog posts, guides and thought leadership written by subject-matter writers and edited in-house.",
                "We match you with writers who know your industry, brief every article from keyword and audience research, and edit for accuracy, clarity and search intent.\n\nEach article is delivered ready to publish with meta data, internal links and image suggestions.",
                new[] { "Your blog is out of date", "Articles don't rank or bring leads", "Generic content that could be from any company", "Subject-matter experts have no time to write" },
                new[] { "Keyword-led content briefs", "Expert-written articles", "Editing and fact-checking", "On-page SEO and internal links", "Meta titles and descriptions", "Publishing in your CMS" },
                new[] { "Semrush", "Surfer", "Google Docs", "WordPress" },
                new[] { "Organic traffic to articles", "Keyword rankings", "Newsletter signups", "Leads from content" },
                new[] { ("How long are your articles?", "Most are 1,200–2,500 words, set by search intent rather than a word count target."),
                        ("Do you use AI to write?", "Our writers may use tools for research, but every article is written, edited and fact-checked by people.") },
                Tiers(800, 1800, new[] { "2 articles per month", "Keyword briefs", "Editing and SEO" },
                    new[] { "5 articles per month", "Subject-matter writers", "CMS publishing", "Quarterly content review" },
                    new[] { "10+ articles per month", "Thought-leadership ghostwriting", "Dedicated editor" }),
                new[] { "seo", "content-marketing-strategy" }),
            new("video-production-youtube", "Video Production & YouTube", "video", "Video that people actually watch to the end.",
                "Short-form social video, brand films, product videos and YouTube channel growth — from script to edit.",
                "Video is the most engaging format on every platform, but only when it's made for that platform. We script, shoot and edit short-form clips, explainers and brand stories, and help you grow a YouTube channel with optimised titles, thumbnails and publishing strategy.\n\nRemote production and creator-led formats keep costs sensible.",
                new[] { "You need video but don't have a production team", "Videos get views but no watch time", "Your YouTube channel isn't growing", "Long approvals kill timely content" },
                new[] { "Concepts and scripts", "Shoot planning and production", "Editing, captions and motion graphics", "Short-form cut-downs for social", "YouTube SEO: titles, descriptions, thumbnails", "Channel analytics reporting" },
                new[] { "Adobe Premiere Pro", "After Effects", "DaVinci Resolve", "YouTube Studio", "TubeBuddy" },
                new[] { "Watch time", "Average view duration", "Subscribers", "Video-assisted conversions" },
                new[] { ("Do you travel for shoots?", "Yes, for brand films and events. Many projects are produced remotely or with creators to keep budgets efficient.") },
                Tiers(1500, 3500, new[] { "4 short-form videos per month", "Scripts and editing", "Captions" },
                    new[] { "8 short videos + 1 long-form", "YouTube optimisation", "Thumbnails", "Monthly analytics" },
                    new[] { "Full channel management", "Brand films", "On-site production days" }),
                new[] { "social-media-management", "influencer-ugc-marketing" }),
            new("podcast-marketing", "Podcast Marketing", "mic", "Launch, grow and monetise a podcast worth listening to.",
                "Podcast strategy, production, guest booking, audiograms and promotion across platforms.",
                "A good podcast builds deep trust with exactly the audience you want. We help you define the show, handle production and editing, book guests, and turn every episode into clips, articles and newsletter content.\n\nWe also place your experts as guests on established shows in your niche.",
                new[] { "You want a podcast but don't know where to start", "Episodes take too long to produce", "Great conversations reach too few people", "No way to connect the show to business results" },
                new[] { "Show concept and format", "Recording setup and remote production", "Editing and show notes", "Clips, audiograms and articles", "Guest booking and outreach", "Launch and growth promotion" },
                new[] { "Riverside", "Descript", "Spotify for Podcasters", "Apple Podcasts Connect" },
                new[] { "Downloads per episode", "Subscriber growth", "Guest appearances booked", "Leads from listeners" },
                new[] { ("Can you get us on other podcasts?", "Yes — podcast guesting is a great way to reach new audiences, and we pitch your experts to relevant shows.") },
                Tiers(1200, 2800, new[] { "2 episodes per month", "Editing and show notes", "Publishing" },
                    new[] { "4 episodes per month", "Clips and audiograms", "Guest booking", "Promotion plan" },
                    new[] { "Weekly show", "Video podcast", "Sponsorship sales support" }),
                new[] { "video-production-youtube", "content-marketing-strategy" }),
        }),
        new("email-messaging", "Email & Messaging", "mail", "Owned channels that drive repeat revenue.", EmailProcess, new ServiceSeed[]
        {
            new("email-marketing-automation", "Email Marketing & Automation", "mail", "Emails people open — and automations that sell while you sleep.",
                "Lifecycle flows, campaigns, segmentation and deliverability management in Klaviyo, HubSpot, Mailchimp and more.",
                "Email is still the highest-ROI channel for most businesses. We build the lifecycle automations that matter — welcome, abandoned cart, post-purchase, win-back, lead nurture — and run a campaign calendar that keeps subscribers engaged.\n\nWe monitor deliverability closely so your emails reach the inbox.",
                new[] { "You only send occasional newsletters", "No automated flows for key moments", "Open rates are falling and emails land in spam", "One message sent to your entire list" },
                new[] { "Email audit and deliverability check", "Lifecycle automation build", "Segmentation strategy", "Campaign design and copy", "A/B testing programme", "Revenue and engagement reporting" },
                new[] { "Klaviyo", "HubSpot", "Mailchimp", "Customer.io", "Litmus" },
                new[] { "Revenue per recipient", "Automated revenue share", "Click rate", "List growth and health" },
                new[] { ("Do you handle design and copy?", "Yes — templates, campaign design, copy and QA are all included."),
                        ("Can you fix our deliverability?", "In most cases. We review authentication (SPF, DKIM, DMARC), list hygiene and sending patterns, and create a recovery plan.") },
                Tiers(900, 2000, new[] { "3 core automations", "2 campaigns per month", "Monthly report" },
                    new[] { "8 automations", "6 campaigns per month", "Segmentation", "A/B testing" },
                    new[] { "Full lifecycle programme", "Weekly campaigns", "Predictive segments", "Dedicated email lead" }, setup: 500),
                new[] { "sms-whatsapp-marketing", "marketing-automation-crm-setup" }, Featured: true),
            new("sms-whatsapp-marketing", "SMS & WhatsApp Marketing", "message-circle", "Timely, permission-based messages with standout response rates.",
                "Compliant SMS and WhatsApp campaigns, automations and two-way conversations that customers welcome.",
                "Messaging channels get read within minutes — which is why they must be used with care. We set up compliant opt-in flows, design automations for high-intent moments like cart abandonment and appointment reminders, and plan campaigns that respect frequency.\n\nWhatsApp Business conversations can also handle sales questions and support.",
                new[] { "You collect phone numbers but never use them", "Messaging without clear consent puts you at risk", "Email alone isn't reaching mobile-first customers", "No automated reminders for bookings or carts" },
                new[] { "Opt-in and consent flows", "SMS and WhatsApp automation", "Campaign planning and copy", "WhatsApp Business setup and templates", "Two-way conversation playbooks", "Performance reporting" },
                new[] { "Klaviyo SMS", "Twilio", "WhatsApp Business Platform", "Attentive" },
                new[] { "Click-through rate", "Revenue per message", "Opt-out rate", "Response time" },
                new[] { ("Is SMS marketing legal?", "Yes, with explicit consent and a clear opt-out in every message. We build consent capture and compliance in from day one.") },
                Tiers(600, 1400, new[] { "1 channel", "3 automations", "2 campaigns per month" },
                    new[] { "SMS and WhatsApp", "6 automations", "4 campaigns per month", "Two-way playbooks" },
                    new[] { "Conversational commerce", "Multi-country compliance", "Dedicated specialist" }, setup: 400),
                new[] { "email-marketing-automation" }),
        }),
        new("brand-web", "Brand & Web", "palette", "A brand people remember and a website that converts.", BrandProcess, new ServiceSeed[]
        {
            new("branding-identity", "Branding & Identity", "palette", "A distinctive brand that makes the right people care.",
                "Brand strategy, naming, logo, visual identity and guidelines — built for digital first.",
                "A strong brand lowers the cost of every other marketing activity. We define your positioning and personality, then design a visual identity — logo, colour, typography, imagery and motion — that works everywhere from favicons to billboards.\n\nYou receive complete guidelines and templates so everyone applies the brand consistently.",
                new[] { "You look like every competitor", "Your brand has outgrown its DIY logo", "Inconsistent visuals across channels", "A merger or new product needs a new identity" },
                new[] { "Brand strategy and positioning", "Naming and tagline (optional)", "Logo and visual identity system", "Brand guidelines", "Social and presentation templates", "Asset library" },
                new[] { "Figma", "Adobe Illustrator", "Adobe InDesign", "Frontify" },
                new[] { "Brand recall", "Consistency across touchpoints", "Direct and branded search traffic" },
                new[] { ("How long does a brand identity take?", "Typically 6–10 weeks from discovery to final guidelines.") },
                Projects(4500, 12000, new[] { "Logo and colour palette", "Typography", "Mini style guide" },
                    new[] { "Brand strategy workshop", "Full visual identity", "Brand guidelines", "Templates" },
                    new[] { "Naming and messaging", "Brand architecture", "Motion identity", "Launch campaign" }),
                new[] { "web-design-development", "copywriting" }),
            new("web-design-development", "Web Design & Development", "layout-template", "Fast, accessible websites built to convert.",
                "Strategy-led web design and development on WordPress, Webflow, Shopify or custom stacks — SEO-ready from day one.",
                "Your website is your hardest-working salesperson. We plan the structure around your buyers' questions, design distinctive pages, and build them to be fast, accessible (WCAG AA) and easy for your team to update.\n\nEvery site launches with analytics, SEO foundations and redirects in place — and we're there after launch to keep improving it.",
                new[] { "Your site looks dated and loads slowly", "Visitors don't convert", "Updating content needs a developer", "A replatform risks losing search traffic" },
                new[] { "UX strategy and sitemap", "Wireframes and visual design", "Responsive development", "CMS setup and training", "SEO and analytics foundations", "Launch, redirects and 30-day support" },
                new[] { "Figma", "WordPress", "Webflow", "Shopify", "React", "Vercel" },
                new[] { "Conversion rate", "Page speed and Core Web Vitals", "Organic traffic after launch", "Bounce rate" },
                new[] { ("Which platform should we use?", "It depends on your team and goals. We recommend WordPress or Webflow for most marketing sites, Shopify for e-commerce and custom builds for complex products."),
                        ("Is the website accessible?", "Yes — we design and test to WCAG 2.1 AA as standard.") },
                Projects(6000, 15000, new[] { "Up to 6 pages", "Template-based design", "CMS setup", "Launch support" },
                    new[] { "Up to 20 pages", "Custom design", "Copywriting support", "SEO migration", "30-day support" },
                    new[] { "Complex or headless builds", "Integrations", "E-commerce", "Ongoing retainer" }),
                new[] { "landing-pages-cro", "technical-seo", "branding-identity" }, Featured: true),
            new("landing-pages-cro", "Landing Pages & CRO", "gauge", "Turn more of your existing traffic into customers.",
                "High-converting landing pages and a structured testing programme based on research, not hunches.",
                "Doubling your conversion rate halves your acquisition cost. We combine analytics, heatmaps, session recordings and user research to find where visitors drop off, then design and test changes that remove friction.\n\nFor campaigns we build focused landing pages that match ad intent and load instantly.",
                new[] { "Paid traffic lands on generic pages", "Visitors abandon forms and checkouts", "Opinions — not data — drive website changes", "You've never run an A/B test" },
                new[] { "Conversion research and analytics audit", "Heatmaps and session recordings", "Hypothesis backlog", "Landing page design and build", "A/B and multivariate tests", "Test results and learnings log" },
                new[] { "GA4", "Hotjar", "Microsoft Clarity", "VWO", "Unbounce", "Figma" },
                new[] { "Conversion rate", "Cost per acquisition", "Revenue per visitor", "Form completion rate" },
                new[] { ("How much traffic do we need to test?", "As a rule of thumb, at least 1,000 conversions per month per page for classic A/B tests. With less, we focus on research-led improvements.") },
                Tiers(1500, 3500, new[] { "2 landing pages per month", "Analytics review", "Monthly recommendations" },
                    new[] { "CRO programme", "2–4 tests per month", "Heatmaps and recordings", "Landing pages included" },
                    new[] { "Multi-site testing", "Personalisation", "User research", "Dedicated CRO lead" }),
                new[] { "ux-audit", "google-ads-ppc", "web-design-development" }),
            new("ux-audit", "UX Audit", "eye", "Find out exactly why visitors don't convert.",
                "An expert review of your website or app's usability, accessibility and conversion journeys, with prioritised fixes.",
                "Our UX specialists review your key journeys against usability heuristics, accessibility standards and conversion best practice, backed by your analytics and session recordings.\n\nYou receive a prioritised report with annotated screenshots and clear recommendations your team can act on immediately.",
                new[] { "High traffic but low conversions", "Customers complain the site is confusing", "Accessibility compliance worries", "A redesign is planned and you want evidence first" },
                new[] { "Heuristic usability review", "Accessibility check against WCAG 2.1 AA", "Analytics and funnel analysis", "Session recording review", "Prioritised recommendations", "Presentation workshop" },
                new[] { "Hotjar", "Microsoft Clarity", "GA4", "axe DevTools", "Figma" },
                new[] { "Task completion", "Conversion rate", "Accessibility issues resolved" },
                new[] { ("What do we get at the end?", "A report with prioritised, annotated findings, quick wins and larger opportunities, plus a workshop with your team.") },
                Projects(1800, 4000, new[] { "1 key journey", "Heuristic review", "Report" },
                    new[] { "Up to 4 journeys", "Accessibility review", "Analytics analysis", "Workshop" },
                    new[] { "Full site or app", "User testing sessions", "Redesign concepts" }),
                new[] { "landing-pages-cro", "web-design-development" }),
        }),
        new("growth", "Growth", "trending-up", "Systems and programmes that compound growth.", GrowthProcess, new ServiceSeed[]
        {
            new("affiliate-partner-marketing", "Affiliate & Partner Marketing", "handshake", "Grow through partners who are paid for results.",
                "Affiliate programme launch and management, partner recruitment, commission strategy and fraud monitoring.",
                "Affiliate and partner programmes let you pay for performance. We choose the right network or platform, design commission structures that reward valuable customers, recruit quality publishers and partners, and monitor for fraud.\n\nThe result is a predictable, low-risk acquisition channel.",
                new[] { "You rely on a handful of expensive channels", "Your affiliate programme is dormant", "Coupon sites claim credit for sales you'd get anyway", "Partner onboarding is manual and slow" },
                new[] { "Programme strategy and commission model", "Network or platform setup", "Partner recruitment", "Creative and promo assets", "Fraud and compliance monitoring", "Partner performance reporting" },
                new[] { "Impact.com", "PartnerStack", "Awin", "CJ" },
                new[] { "Affiliate revenue", "Active partners", "Cost per acquisition", "Incremental share of sales" },
                new[] { ("Do you work with influencers as affiliates?", "Yes, and our creator network can join commission-based programmes alongside publishers.") },
                Tiers(1000, 2200, new[] { "Programme setup", "20 partners recruited", "Monthly report" },
                    new[] { "Active recruitment", "Partner activation campaigns", "Fraud monitoring", "Bi-weekly calls" },
                    new[] { "Global programmes", "Strategic partnerships", "Dedicated partner manager" }, setup: 1000),
                new[] { "influencer-ugc-marketing", "ecommerce-growth" }),
            new("marketing-automation-crm-setup", "Marketing Automation & CRM Setup", "workflow", "A CRM your sales and marketing teams actually use.",
                "HubSpot, Salesforce and Pipedrive setup, lead scoring, nurture workflows and integrations.",
                "Growth stalls when leads fall through the cracks. We design your lifecycle stages, implement or clean up your CRM, build lead scoring and nurture workflows, and connect your website, ads and email platforms so every lead is tracked from first touch to closed deal.\n\nWe document everything and train your team.",
                new[] { "Leads live in spreadsheets and inboxes", "Marketing and sales disagree on what a qualified lead is", "No visibility of the full funnel", "Your CRM is cluttered and nobody trusts it" },
                new[] { "Lifecycle and pipeline design", "CRM implementation or clean-up", "Lead scoring and routing", "Nurture workflows", "Integrations with forms, ads and email", "Documentation and training" },
                new[] { "HubSpot", "Salesforce", "Pipedrive", "Zapier", "Make" },
                new[] { "Lead-to-customer rate", "Speed to lead", "Pipeline velocity", "Data completeness" },
                new[] { ("Can you migrate us from another CRM?", "Yes. We plan data mapping, clean-up and migration to minimise disruption.") },
                Projects(3000, 8000, new[] { "CRM setup", "Pipeline and properties", "Form integration", "Training" },
                    new[] { "Everything in Starter", "Lead scoring", "5 nurture workflows", "Ad and email integrations" },
                    new[] { "Complex migrations", "Custom objects", "Revenue attribution", "Ongoing admin" }),
                new[] { "email-marketing-automation", "lead-generation" }),
            new("ecommerce-growth", "E-commerce Growth", "store", "More traffic, higher conversion and bigger baskets.",
                "Integrated e-commerce growth programmes across paid media, CRO, email, retention and marketplaces.",
                "E-commerce growth comes from pulling many levers at once. We look at your acquisition mix, product pages, checkout, email and SMS flows, and customer lifetime value, then run a coordinated programme with one accountable team.\n\nYou get a single dashboard showing contribution margin, not just revenue.",
                new[] { "Growth depends on ever-rising ad spend", "Low repeat purchase rate", "Checkout abandonment", "Disconnected agencies for ads, email and web" },
                new[] { "E-commerce growth audit", "Channel mix and budget plan", "Product page and checkout CRO", "Retention and loyalty programmes", "Marketplace strategy", "Profit-focused dashboard" },
                new[] { "Shopify", "Klaviyo", "Google Merchant Center", "Triple Whale", "Recharge" },
                new[] { "Revenue", "Customer lifetime value", "Repeat purchase rate", "Marketing efficiency ratio" },
                new[] { ("Do we need to use all your services?", "No. We recommend the mix that fits your stage, and integrate with your existing partners.") },
                Tiers(3500, 7500, new[] { "Growth audit", "2 channels managed", "Monthly strategy call" },
                    new[] { "4 channels managed", "CRO programme", "Retention flows", "Weekly reporting" },
                    new[] { "Full-funnel team", "International expansion", "Dedicated growth lead" }),
                new[] { "shopping-ecommerce-ads", "email-marketing-automation", "landing-pages-cro" }),
            new("lead-generation", "Lead Generation", "magnet", "A predictable pipeline of qualified leads.",
                "Multi-channel B2B and B2C lead generation: paid media, content offers, landing pages and nurture.",
                "We build lead generation systems end to end: the offer, the landing page, the traffic and the follow-up. Leads are scored and routed to your team in real time, and we optimise for qualified leads and closed revenue — not form fills.\n\nWe agree lead quality criteria with your sales team up front.",
                new[] { "Sales teams are starved of leads", "Lead quality is poor", "Cost per lead keeps rising", "No follow-up process for new leads" },
                new[] { "Offer and lead magnet development", "Landing pages and forms", "Paid media campaigns", "Lead scoring and routing", "Nurture sequences", "Pipeline reporting" },
                new[] { "Google Ads", "LinkedIn Campaign Manager", "HubSpot", "Unbounce", "Zapier" },
                new[] { "Cost per qualified lead", "Lead-to-opportunity rate", "Pipeline generated", "Speed to lead" },
                new[] { ("Do you guarantee a number of leads?", "We forecast lead volumes from benchmarks and your budget, and report transparently — but we don't sell lead guarantees that encourage low-quality volume.") },
                Tiers(2000, 4500, new[] { "1 channel", "1 lead magnet", "Landing page", "CRM routing" },
                    new[] { "2–3 channels", "Monthly new offers", "Nurture sequences", "Weekly reporting" },
                    new[] { "Account-based marketing", "SDR enablement", "Dedicated growth lead" }, setup: 750),
                new[] { "marketing-automation-crm-setup", "google-ads-ppc", "tiktok-linkedin-ads" }),
        }),
        new("reputation-pr", "Reputation & PR", "shield-check", "Earn trust before customers ever talk to you.", ReputationProcess, new ServiceSeed[]
        {
            new("online-reputation-management", "Online Reputation Management", "shield-check", "More great reviews — and a calm plan for the bad ones.",
                "Review generation, monitoring and response across Google, Trustpilot, app stores and industry sites.",
                "Customers read reviews before they buy. We set up compliant review programmes that ask happy customers at the right moment, monitor every platform, and respond to feedback promptly and professionally.\n\nIf you're dealing with unfair or misleading content, we build a measured response and suppression plan.",
                new[] { "Your rating is lower than your service deserves", "Negative reviews go unanswered", "Damaging search results for your brand name", "No visibility across review platforms" },
                new[] { "Reputation audit", "Review generation programme", "Monitoring across platforms", "Response management", "Branded search result improvement", "Monthly sentiment reporting" },
                new[] { "Google Business Profile", "Trustpilot", "Birdeye", "Brandwatch" },
                new[] { "Average rating", "Review volume", "Response rate", "Share of positive branded results" },
                new[] { ("Can you remove negative reviews?", "We can flag reviews that break platform policies. Genuine reviews can't be removed — but a thoughtful response and more positive reviews change the picture.") },
                Tiers(600, 1400, new[] { "2 review platforms", "Review requests", "Monitoring" },
                    new[] { "All platforms", "Response management", "Monthly reporting" },
                    new[] { "Multi-location brands", "Search result suppression", "Crisis support" }),
                new[] { "local-seo-google-business-profile", "digital-pr-outreach" }),
            new("digital-pr-outreach", "Digital PR & Outreach", "newspaper", "Coverage and links from publications your customers read.",
                "Data-led stories, expert commentary and outreach that earn media coverage and authoritative backlinks.",
                "Digital PR builds brand awareness and search authority at the same time. We create newsworthy campaigns — original data, expert commentary, reactive stories — and pitch them to journalists who cover your space.\n\nEvery campaign is measured by coverage quality, links earned and referral traffic.",
                new[] { "Journalists have never heard of you", "Link building feels spammy", "Competitors dominate industry coverage", "Your experts have insight but no platform" },
                new[] { "PR strategy and story ideation", "Data and survey campaigns", "Expert commentary and reactive PR", "Journalist outreach", "Coverage and link reporting", "Thought-leadership placements" },
                new[] { "Muck Rack", "Cision", "Qwoted", "Ahrefs" },
                new[] { "Coverage secured", "Authoritative links", "Referral traffic", "Branded search growth" },
                new[] { ("How many links will we get?", "It varies by campaign and industry; we share realistic ranges during planning and report every piece of coverage.") },
                Tiers(2000, 4500, new[] { "1 campaign per quarter", "Reactive commentary", "Monthly report" },
                    new[] { "1 campaign per month", "Expert placements", "Link reporting" },
                    new[] { "Always-on PR team", "International outreach", "Crisis communications" }),
                new[] { "seo", "online-reputation-management" }),
        }),
        new("strategy-analytics", "Strategy & Analytics", "compass", "Clarity on what to do next — and proof that it worked.", StrategyProcess, new ServiceSeed[]
        {
            new("marketing-strategy-consulting", "Marketing Strategy & Consulting", "compass", "A clear, costed plan for growth.",
                "Senior marketing strategy: positioning, channel mix, budgets, targets and the team to deliver them.",
                "Before spending more, know where growth will come from. Our strategists review your market, customers, data and current marketing, then build a practical plan: which channels, what budget, which targets and who does what.\n\nAvailable as a one-off project or as fractional CMO support.",
                new[] { "Marketing activity without a plan", "Budget spread too thinly across channels", "Leadership wants a growth plan for investors", "You need senior marketing leadership but not a full-time hire" },
                new[] { "Market and competitor analysis", "Customer research and personas", "Positioning and messaging", "Channel mix and budget model", "90-day action plan", "KPI framework" },
                new[] { "Miro", "Notion", "GA4", "Looker Studio" },
                new[] { "Customer acquisition cost", "Marketing-sourced revenue", "Payback period" },
                new[] { ("Do you offer fractional CMO services?", "Yes — a senior strategist can lead your marketing part-time, working with your team and ours.") },
                Projects(4000, 9000, new[] { "Marketing audit", "Channel recommendations", "90-day plan" },
                    new[] { "Everything in Starter", "Customer research", "Positioning", "Budget model" },
                    new[] { "Fractional CMO (monthly)", "Team and agency leadership", "Board reporting" }),
                new[] { "analytics-tracking-setup", "reporting-dashboards" }),
            new("analytics-tracking-setup", "Analytics & Tracking Setup (GA4, GTM, pixels)", "activity", "Data you can trust for every marketing decision.",
                "GA4, Google Tag Manager, ad pixels and server-side tracking implemented correctly — with consent built in.",
                "Bad data leads to bad decisions. We audit your current tracking, design a measurement plan, and implement GA4, Google Tag Manager, Meta, TikTok and LinkedIn pixels and conversion APIs — respecting your cookie consent choices.\n\nEvery event is documented and tested so your team knows exactly what's measured.",
                new[] { "Numbers in GA4 don't match your sales", "Conversions are double-counted or missing", "Tags fire before visitors consent", "Nobody knows what's being tracked" },
                new[] { "Tracking audit", "Measurement plan", "GA4 and GTM implementation", "Ad pixels and conversion APIs", "Consent mode setup", "Tracking documentation and QA" },
                new[] { "Google Analytics 4", "Google Tag Manager", "Meta Conversions API", "Server-side GTM", "Consent management platforms" },
                new[] { "Tracking accuracy", "Conversion match rate", "Consent-compliant tag coverage" },
                new[] { ("Will tracking respect cookie consent?", "Yes. We implement consent mode and only fire marketing and analytics tags after the visitor agrees.") },
                Projects(1500, 3500, new[] { "GA4 and GTM setup", "Up to 10 events", "Documentation" },
                    new[] { "Measurement plan", "Ad pixels and CAPI", "Consent mode", "E-commerce tracking" },
                    new[] { "Server-side tagging", "Multi-domain tracking", "Data warehouse export" }),
                new[] { "reporting-dashboards", "marketing-strategy-consulting" }),
            new("reporting-dashboards", "Reporting & Dashboards", "bar-chart-3", "One source of truth for marketing performance.",
                "Automated dashboards combining ads, analytics, CRM and sales data — built for decisions, not decoration.",
                "Stop copying numbers between spreadsheets. We connect your ad platforms, analytics, CRM and e-commerce data into clear dashboards for executives, marketers and clients, refreshed automatically.\n\nEvery metric is defined, so everyone reads the numbers the same way.",
                new[] { "Hours lost building reports every month", "Every platform claims credit for the same sale", "Leadership can't see marketing ROI", "Metrics are defined differently by each team" },
                new[] { "KPI and metric definitions", "Data source connections", "Executive and channel dashboards", "Automated scheduled reports", "Attribution views", "Training session" },
                new[] { "Looker Studio", "Power BI", "Supermetrics", "BigQuery" },
                new[] { "Time saved on reporting", "Decisions backed by data", "Marketing ROI visibility" },
                new[] { ("Which tools do you use?", "Mostly Looker Studio and Power BI, with Supermetrics or BigQuery for data connections — or your existing BI stack.") },
                Tiers(500, 1200, new[] { "1 dashboard", "Up to 4 data sources", "Monthly refresh check" },
                    new[] { "3 dashboards", "Up to 10 data sources", "Attribution views", "Monthly insights" },
                    new[] { "Data warehouse", "Custom attribution", "Dedicated analyst" }, setup: 1500),
                new[] { "analytics-tracking-setup", "marketing-strategy-consulting" }),
        }),
    };
}
