using System.Text.RegularExpressions;

namespace OptimizeAll.Api.Modules.Files;

public sealed class StorageOptions
{
    public const string Section = "Storage";

    /// <summary>Directory for uploaded files. Relative paths resolve against the content root. Never under the web root.</summary>
    public string RootPath { get; set; } = "storage/files";
}

/// <summary>Private blob storage. Keys are generated by the server (<see cref="NewKey"/>); callers never supply paths.</summary>
public interface IFileStorage
{
    string NewKey(DateTime nowUtc, string extension);
    Task WriteAsync(string key, ReadOnlyMemory<byte> content, CancellationToken ct = default);
    Stream? OpenRead(string key);
    void Delete(string key);
}

public sealed partial class LocalFileStorage : IFileStorage
{
    private readonly string _root;

    public LocalFileStorage(Microsoft.Extensions.Options.IOptions<StorageOptions> options, IHostEnvironment environment)
    {
        var configured = string.IsNullOrWhiteSpace(options.Value.RootPath) ? "storage/files" : options.Value.RootPath;
        _root = Path.GetFullPath(Path.IsPathRooted(configured) ? configured : Path.Combine(environment.ContentRootPath, configured));
        Directory.CreateDirectory(_root);
    }

    public string NewKey(DateTime nowUtc, string extension)
    {
        if (!ExtensionRegex().IsMatch(extension))
            throw new ArgumentException("Unsupported extension.", nameof(extension));
        return $"{nowUtc:yyyy}/{nowUtc:MM}/{Guid.NewGuid():N}{extension}";
    }

    public async Task WriteAsync(string key, ReadOnlyMemory<byte> content, CancellationToken ct = default)
    {
        var path = Resolve(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await using var stream = new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.None, 81920, useAsync: true);
        await stream.WriteAsync(content, ct);
    }

    public Stream? OpenRead(string key)
    {
        var path = Resolve(key);
        return File.Exists(path)
            ? new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, useAsync: true)
            : null;
    }

    public void Delete(string key)
    {
        var path = Resolve(key);
        if (File.Exists(path)) File.Delete(path);
    }

    /// <summary>Maps a key to a path inside the root, rejecting anything that is not a server-generated key.</summary>
    private string Resolve(string key)
    {
        if (!KeyRegex().IsMatch(key))
            throw new InvalidOperationException("Invalid storage key.");
        var full = Path.GetFullPath(Path.Combine(_root, key));
        if (!full.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal))
            throw new InvalidOperationException("Invalid storage key.");
        return full;
    }

    [GeneratedRegex(@"^\d{4}/\d{2}/[0-9a-f]{32}\.(png|jpg|webp|pdf|mp4|vtt)$")]
    private static partial Regex KeyRegex();

    [GeneratedRegex(@"^\.(png|jpg|webp|pdf|mp4|vtt)$")]
    private static partial Regex ExtensionRegex();
}
