#!/usr/bin/env bash
# Prints freshly generated secrets for an Optimize All environment.
#
# Usage:
#   scripts/generate-secrets.sh              # staging compose keys (deploy/.env.staging format)
#   scripts/generate-secrets.sh --staging    # same as above
#   scripts/generate-secrets.sh --aspnet     # ASP.NET Core env var names (Jwt__SigningKey=...), for production/secret stores
#   scripts/generate-secrets.sh --help
#
# Example:
#   cp deploy/.env.staging.example deploy/.env.staging
#   scripts/generate-secrets.sh >> deploy/.env.staging     # later lines override the placeholders above them
#
# Values are printed to stdout only; nothing is written to disk. Store production values in your secret
# manager, never in git. Passwords are alphanumeric so they are safe inside MySQL connection strings.
set -euo pipefail

usage() { sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'; }

format="staging"
case "${1:-}" in
  ""|--staging) format="staging" ;;
  --aspnet) format="aspnet" ;;
  -h|--help) usage; exit 0 ;;
  *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
esac

command -v openssl >/dev/null 2>&1 || { echo "openssl is required" >&2; exit 1; }

# Random alphanumeric string of length $1.
alnum() {
  local len="$1" out=""
  while [ "${#out}" -lt "$len" ]; do
    out+="$(openssl rand -base64 64 | tr -dc 'A-Za-z0-9')"
  done
  printf '%s' "${out:0:$len}"
}

jwt_key="$(openssl rand -base64 48 | tr -d '\n')"   # 384 bits
hash_salt="$(openssl rand -hex 32)"                  # 256 bits
postback_secret="$(openssl rand -hex 32)"
mysql_root_password="$(alnum 32)"
mysql_password="$(alnum 32)"
# Satisfies the password policy (length >= 10, not common, varied characters).
admin_password="$(alnum 20)-Oa9"

echo "# Generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
if [ "$format" = "staging" ]; then
  cat <<EOF
MYSQL_ROOT_PASSWORD=${mysql_root_password}
MYSQL_PASSWORD=${mysql_password}
JWT_SIGNING_KEY=${jwt_key}
HASH_SALT=${hash_salt}
POSTBACK_SECRET=${postback_secret}
BOOTSTRAP_ADMIN_PASSWORD=${admin_password}
EOF
else
  cat <<EOF
# MySQL user password (put it into ConnectionStrings__Default) and root password (for provisioning only).
MYSQL_ROOT_PASSWORD=${mysql_root_password}
MYSQL_PASSWORD=${mysql_password}
Jwt__SigningKey=${jwt_key}
Security__HashSalt=${hash_salt}
Tracking__PostbackSecret=${postback_secret}
# One-time bootstrap admin password; change it after first sign-in and then remove it from the environment.
Bootstrap__AdminPassword=${admin_password}
EOF
fi
