import { expect, test } from '@playwright/test';
import { API_URL, axeViolations, runId, watchErrors } from './support/agency';

/**
 * Public agency website, anonymous visitor: home → services → service detail, blog → post, careers, the contact form
 * (with the anti-spam minimum fill time) and the API-generated robots.txt / sitemap.xml. No console errors anywhere;
 * axe (WCAG 2.1 A/AA) on the home page.
 */
test.describe('public website', () => {
  test('home, services, blog, careers and contact without console errors', async ({ page }) => {
    const errors = watchErrors(page);

    await page.goto('/');
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
    await expect(page.getByRole('navigation', { name: 'Main' })).toBeVisible();
    await expect(page.getByRole('region', { name: 'Every channel, one accountable team' })).toBeVisible();
    expect(await axeViolations(page), 'axe violations on the home page').toEqual([]);

    // Services list → detail.
    await page.getByRole('main').getByRole('link', { name: 'All services' }).click();
    await expect(page).toHaveURL(/\/services$/);
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
    const seo = page.getByRole('main').getByRole('link', { name: 'SEO', exact: true }).first();
    await seo.click();
    await expect(page).toHaveURL(/\/services\/seo$/);
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
    await expect(
      page.getByRole('navigation', { name: 'Breadcrumb' }).getByRole('link', { name: 'Services' }),
    ).toBeVisible();

    // Blog list → post.
    await page.goto('/blog');
    await expect(
      page.getByRole('heading', { level: 1, name: 'Marketing playbooks that actually work' }),
    ).toBeVisible();
    const firstPost = page
      .getByRole('main')
      .getByRole('article')
      .first()
      .getByRole('heading', { level: 2 })
      .getByRole('link');
    const title = (await firstPost.textContent())!.trim();
    await firstPost.click();
    await expect(page).toHaveURL(/\/blog\/[\w-]+$/);
    await expect(page.getByRole('heading', { level: 1, name: title })).toBeVisible();

    // Careers.
    await page.goto('/careers');
    const roles = page.getByRole('region', { name: 'Open roles' });
    await expect(roles.getByRole('article').first()).toBeVisible();
    const role = roles.getByRole('article').first().getByRole('heading', { level: 3 }).getByRole('link');
    const roleTitle = (await role.textContent())!.trim();
    await role.click();
    await expect(page).toHaveURL(/\/careers\/[\w-]+$/);
    await expect(page.getByRole('heading', { level: 1, name: roleTitle })).toBeVisible();

    // Contact form. The form token proves a minimum fill time (FormGuard.MinFillSeconds): wait until the token the
    // page fetched is old enough rather than sleeping a fixed time.
    const tokenResponse = page.waitForResponse(
      (r) => r.url().includes('/api/v1/public/forms/token') && r.ok(),
    );
    await page.goto('/contact');
    const token = (await (await tokenResponse).json()) as { minFillSeconds: number };
    const tokenAt = Date.now();
    const form = page.getByRole('form', { name: 'Contact form' });
    const id = runId();
    await form.getByLabel('Full name').fill(`Casey Contact ${id}`);
    await form.getByLabel('Work email').fill(`casey.${id}@e2e.optimizeall.test`);
    await form.getByLabel('Company').fill('E2E Widgets');
    await form
      .getByLabel('How can we help?')
      .fill('We would like a proposal for SEO and paid media next quarter.');
    await form.getByRole('checkbox', { name: /^I agree that Optimize All may use/ }).check();
    await expect
      .poll(() => Date.now() - tokenAt, { message: 'form token older than the minimum fill time' })
      .toBeGreaterThanOrEqual(token.minFillSeconds * 1000);
    await form.getByRole('button', { name: 'Send message' }).click();
    await expect(page.getByRole('heading', { name: 'Thanks — message received' })).toBeVisible();

    errors.expectClean('the public website');
  });

  test('robots.txt and sitemap.xml are generated by the API', async ({ request }) => {
    const robots = await request.get(`${API_URL}/robots.txt`);
    expect(robots.ok()).toBe(true);
    const robotsText = await robots.text();
    expect(robotsText).toMatch(/^User-agent: \*/m);
    // Areas are closed exactly (`/agency$` and `/agency/…`), never as a bare prefix (docs/SEO_CRO.md § 9.7).
    expect(robotsText).toMatch(/^Disallow: \/agency\$$/m);
    expect(robotsText).toMatch(/^Disallow: \/agency\/$/m);
    expect(robotsText).toMatch(/^Disallow: \/client\$$/m);
    expect(robotsText).toMatch(/^Sitemap: \S+sitemap\.xml$/m);

    const sitemap = await request.get(`${API_URL}/api/v1/public/sitemap.xml`);
    expect(sitemap.ok()).toBe(true);
    expect(sitemap.headers()['content-type']).toMatch(/xml/);
    const xml = await sitemap.text();
    expect(xml).toContain('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">');
    for (const path of ['/services', '/services/seo', '/blog', '/careers', '/contact']) {
      expect(xml, `sitemap lists ${path}`).toMatch(
        new RegExp(`<loc>[^<]*${path.replace(/\//g, '\\/')}</loc>`),
      );
    }
    // Portals are never in the sitemap.
    expect(xml).not.toMatch(/<loc>[^<]*\/(agency|client|admin)(\/|<)/);
  });
});
